### PR TITLE
Permission support in config panel

### PR DESCRIPTION
**Pull request by rosbeef**
support permissions in config panel

### CODE REVIEW

**Comment by rosbeef** [comment]
you can merge and test, i have tested on my own fork.
i could not test your branch as i need to make modification in the install script for my armhf platform

**Comment by rosbeef** [comment]
i'm not sure about that upgrade will work as previous values were not escaped to be well shown in the config panel.
config panel need @ and * to be escaped by \

i can not test the upgrade for now but the code should be somthing like this:
```
...
if [ -z "$enable_relaybot" ]
then
    enable_relaybot="true"
    ynh_app_setting_set --app=$app --key=enable_relaybot --value=$enable_relaybot
fi

if [ -z "$listuser" ]
then
    listuser=$(ynh_app_setting_get --app=$app --key=botusers)
    ynh_app_setting_set --app=$app --key=listuser --value=$listuser
    ynh_app_setting_delete --app=$app --key=botusers
fi
listuser_esc=$(echo ${listuser} | sed -r "s/([@*])/\\\\\1/g" | sed -r "s/(\\\\)/\\\/g")
ynh_app_setting_set --app=$app --key=listuser --value=${listuser_esc}

if [ -z "$listrelay" ]
then
    listrelay="*"
    ynh_app_setting_set --app=$app --key=listrelay --value=$listrelay
fi
listrelay_esc=$(echo ${listrelay} | sed -r "s/([@*])/\\\\\1/g" | sed -r "s/(\\\\)/\\\/g")
ynh_app_setting_set --app=$app --key=listrelay --value=${listrelay_esc}


if [ -z "$listadmin" ]
then
    listadmin=$(ynh_app_setting_get --app=$app --key=botadmin)
    ynh_app_setting_set --app=$app --key=listadmin --value=$listadmin
    ynh_app_setting_delete --app=$app --key=botadmin
fi
listadmin_esc=$(echo ${listadmin} | sed -r "s/([@*])/\\\\\1/g" | sed -r "s/(\\\\)/\\\/g")
ynh_app_setting_set --app=$app --key=listadmin --value=${listadmin_esc}
...
```

**Comment by gautz** [comment]
@nathanael-h can you have a look ?

**Comment by nathanael-h** [comment]
Yes, I'll try to free some time for that.

**Comment by rosbeef** [comment]
sorry, i was talking with aleks on the yunohost-dev matrix room about a situation requiering to ask user escape caracteres @#* to make config panel work. and it illuminates me.
So i tested and see that using no getters the situation is not occuring.
My question is why did you managed to make getter which will get values directly from the config file instead of the standard way directly in the ynh app database ?

**Comment by nathanael-h** [comment]
> why did you managed to make getter which will get values directly from the config file instead of the standard way directly in the ynh app database ?

Hum, no reason, I think I copied pasted this from config_panel in mautrix_whatsapp_ynh sometimes. 

So no need, I merge this PR so that we can move forward.

**Pull request merged**
