### PR TITLE
 make config panel permissions work and install works on armhf

### PR DESCRIPTION
**Pull request by rosbeef**
## Problem

- getter setter does not work for permissions

## Solution

- use sed to make getter setter works
Additionaly i made a modification to make install, upgrade, restore works on armhf armel

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by rosbeef** [comment]
@nathanael-h  sorry i'm learning github.
how i can revert a modification ?
i understood that that its not the right way to make 2 modifications in the same pr

**Comment by nathanael-h** [comment]
You can simply create another branch from nathanael-h/config-panel, then commit modifications on it. Close this PR. And open a new PR with the newly created branch.

**Comment by nathanael-h** [comment]
Or I can cherry-pick some commits

**Comment by rosbeef** [comment]
ok i will did it from start

**Pull request closed without merging**
